// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gewsmnzplglpvnaxfmcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdld3NtbnpwbGdscHZuYXhmbWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODIyNzIsImV4cCI6MjA2Mzg1ODI3Mn0.qJLmb5UA7HbHfZ77fqDh0S2hw0NZdBGki6K308wNUzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);